name: codo
description: "Todo list for College"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  page_transition: ^2.2.1
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.4.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  bloc: ^9.0.1
  audioplayers: ^6.5.1
  flutter_colorpicker: ^1.1.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700