// Mocks generated by Mockito 5.4.6 from annotations
// in codo/test/features/menu/domain/usecases/menu_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:codo/core/error/failures.dart' as _i5;
import 'package:codo/features/menu/domain/entities/tag_menu_item.dart' as _i6;
import 'package:codo/features/menu/domain/repositories/menu_repository.dart'
    as _i3;
import 'package:codo/features/menu/domain/usecases/update_tags_order.dart'
    as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MenuRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMenuRepository extends _i1.Mock implements _i3.MenuRepository {
  MockMenuRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getMyDayAmount() =>
      (super.noSuchMethod(
            Invocation.method(#getMyDayAmount, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
              _FakeEither_0<_i5.Failure, int>(
                this,
                Invocation.method(#getMyDayAmount, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getTaskAmount() =>
      (super.noSuchMethod(
            Invocation.method(#getTaskAmount, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
              _FakeEither_0<_i5.Failure, int>(
                this,
                Invocation.method(#getTaskAmount, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TagMenuItem>>>
  getTagMenuItems() =>
      (super.noSuchMethod(
            Invocation.method(#getTagMenuItems, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.TagMenuItem>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.TagMenuItem>>(
                    this,
                    Invocation.method(#getTagMenuItems, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TagMenuItem>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateTagsOrder(
    _i7.UpdateTagsOrderParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTagsOrder, [params]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateTagsOrder, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
