// Mocks generated by Mockito 5.4.6 from annotations
// in codo/test/features/tag/domain/usecases/tag_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:codo/core/error/failures.dart' as _i5;
import 'package:codo/features/tag/domain/entities/tag.dart' as _i6;
import 'package:codo/features/tag/domain/repositories/tag_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TagRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagRepository extends _i1.Mock implements _i3.TagRepository {
  MockTagRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tag>>> getTags() =>
      (super.noSuchMethod(
            Invocation.method(#getTags, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tag>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tag>>(
                    this,
                    Invocation.method(#getTags, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tag>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> createTag(
    String? title,
    String? backgroundHex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTag, [title, backgroundHex]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#createTag, [title, backgroundHex]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> renameTag(
    int? id,
    String? newTitle,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameTag, [id, newTitle]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#renameTag, [id, newTitle]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteTagOnly(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTagOnly, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteTagOnly, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteTagWithTasks(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTagWithTasks, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteTagWithTasks, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
