// Mocks generated by Mockito 5.4.6 from annotations
// in codo/test/features/task/data/repositories/task_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:codo/features/task/data/datasources/task_local_data_source.dart'
    as _i2;
import 'package:codo/features/task/data/models/task_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TaskLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskLocalDataSource extends _i1.Mock
    implements _i2.TaskLocalDataSource {
  MockTaskLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TaskModel>> getMyDay() =>
      (super.noSuchMethod(
            Invocation.method(#getMyDay, []),
            returnValue: _i3.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i3.Future<List<_i4.TaskModel>>);

  @override
  _i3.Future<List<_i4.TaskModel>> getAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTasks, []),
            returnValue: _i3.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i3.Future<List<_i4.TaskModel>>);

  @override
  _i3.Future<List<_i4.TaskModel>> getTasksByCategory(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByCategory, [id]),
            returnValue: _i3.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i3.Future<List<_i4.TaskModel>>);

  @override
  _i3.Future<bool> insertTask(_i4.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#insertTask, [task]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteTask(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> taskChecked(int? id, bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#taskChecked, [id, status]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
