name: Mobile CI

on: 
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                distribution: 'oracle'
                java-version: '17'

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.41.9

            - name: flutter pub get
              run: flutter pub get

            - name: flutter analyze
              run: flutter analyze --no-fatal-infos

            - name: flutter test
              run: flutter test

            - name: Build APK
              run: flutter build apk --release
